### ISSUE TITLE
Formatting of multi-line `seq!` macro

### ISSUE THREAD

**Issue by mmcloughlin** [verus-lang/verusfmt#42]
`verusfmt` 0.2.8 formats:

```rs
use vstd::prelude::*;

verus! {

proof fn f() {
    let s =
        seq![
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    ];
}

} // verus!
```

This occurs with two lines or more. With only one you get:

```rs
proof fn f() {
    let s = seq![
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    ];
}
```

**Comment by parno** [comment]
Indeed, `verusfmt` support for macro invocations is rather limited at present, unfortunately.  However, our current [policy](https://github.com/verus-lang/verusfmt?tab=readme-ov-file#contributing) is that requests/suggestions for formatting improvements are best handled through PRs, which are most welcome.  We're trying to reserve GitHub Issues for functional bugs, so I'll close this for now.
