### ISSUE TITLE
Unsupported parsing object 'const_arg' when I used seq macro to repeat some codes inside verus macro.

### ISSUE THREAD

**Issue by ziqiaozhou** [verus-lang/verusfmt#76]
Below is the error message I received when I fun tools/fmt.sh in https://github.com/microsoft/verismo. I guess it is due to the use of a macro inside verus macro.

ERROR Unsupported parsing object 'const_arg', starting at line 12, col 35: 512
thread 'main' panicked at src/lib.rs:437:5:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed at /home/ziqiaozhou/verismo/tools/../source/verismo/src/pgtable_e/def.rs
Error:   × Failed to parse
    ╭─[/home/ziqiaozhou/verismo/tools/../source/verismo/src/tspec/security/sectype.rs:60:1]
 60 │     open spec fn is_fullsecret(&self) -> bool {
 61 │         #(&&& self.is_fullsecret_to(N))*
    ·          ┬
    ·          ╰── here
 62 │     }
    ╰────
  help: Expected one of: COMMENT, bang_str

Failed at /home/ziqiaozhou/verismo/tools/../source/verismo/src/tspec/security/sectype.rs
Error:   × Failed to parse
     ╭─[/home/ziqiaozhou/verismo/tools/../source/verismo/src/tspec/math/bits_p.rs:321:1]
 321 │         forall |a: u64, b: u64| b < 64 ==> ((a & BIT64!(b) ==  BIT64!(b)) || (a & BIT64!(b) == 0)),
 322 │         #(
     ·          ┬
     ·          ╰── here
 323 │         BIT64!(N as u64) == POW2!(N),
     ╰────
  help: Expected one of: COMMENT, bang_str

Failed at /home/ziqiaozhou/verismo/tools/../source/verismo/src/tspec/math/bits_p.rs
Error:   × Failed to parse
    ╭─[/home/ziqiaozhou/verismo/tools/../source/verismo/src/tspec/math/integer.rs:34:1]
 34 │         requires
 35 │             #(
    ·              ┬
    ·              ╰── here
 36 │                 !spec_has_bit_set(input, N),
    ╰────
  help: Expected one of: COMMENT, bang_str

Failed at /home/ziqiaozhou/verismo/tools/../source/verismo/src/allocator/buddy_new.rs
   0.025630324s ERROR Unsupported parsing object 'const_arg', starting at line 47, col 59: 66
thread 'main' panicked at src/lib.rs:437:5:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed at /home/ziqiaozhou/verismo/tools/../source/verismo/src/debug/ghcb_print.rs
   0.007946223s ERROR Unsupported parsing object 'const_arg', starting at line 108, col 29: 32
thread 'main' panicked at src/lib.rs:437:5:
not yet implemented

**Comment by parno** [comment]
Is it possible you're using an old version of `verusfmt`?  We added support for `const_arg` about a month ago in commit d25af4c.  If you're using the latest version and still hitting an issue, can you share a small example of the code causing the issue?

**Comment by jaybosamiya-ms** [comment]
I agree and believe this issue has already been fixed. Closing this issue for now as done, but please feel free to reopen with an example after testing on latest verusfmt.
